[build-system]
requires = ["hatchling>=1.25.0"]
build-backend = "hatchling.build"

[project]
name = "integritas-mcp-server"
version = "0.1.0"
description = "Integritas MCP Server (Minima hash stamping) – stamp tool only"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Integritas", email = "dev@integritas.example" }]
license = { text = "MIT" }
dependencies = [
  "mcp>=1.0.0",            # Python MCP SDK (FastMCP)
  "httpx>=0.27.0",
  "pydantic>=2.7.0",
  "pydantic-settings>=2.2.1",
  "structlog>=24.1.0",
  "tenacity>=8.2.3",
  "fastapi>=0.115.0",
  "uvicorn>=0.30.0",
]

[project.optional-dependencies]
dev = [
  "pytest>=8.0.0",
  "pytest-asyncio>=0.23.5",
  "respx>=0.21.1",
  "anyio>=4.4.0",
  "ruff>=0.5.0",
  "mypy>=1.10.0",
]

[project.scripts]
integritas-mcp = "integritas_mcp_server.cli:run"

[tool.ruff]
line-length = 100

[tool.pytest.ini_options]
asyncio_mode = "auto"
