name: Release
on:
  push:
    tags: ["v*.*.*"]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install .[dev]
      - run: python scripts/generate_schemas.py
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            schemas/stamp.request.schema.json
            schemas/stamp.response.schema.json
            schemas/tools.manifest.json
